### ISSUE TITLE
当post数据超过4058字节后，接收不到后面的数据，数据会被截断，爆出异常，该如何解决？

### ISSUE THREAD

**Issue by napoleaon** [yanzhenjie/AndServer#109]
W/System.err: java.net.SocketTimeoutException
W/System.err:     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
W/System.err:     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
W/System.err:     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
W/System.err:     at org.apache.httpcore.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
W/System.err:     at org.apache.httpcore.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
W/System.err:     at org.apache.httpcore.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
W/System.err:     at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:130)
W/System.err:     at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:54)
W/System.err:     at org.apache.httpcore.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
W/System.err:     at org.apache.httpcore.impl.DefaultBHttpServerConnection.receiveRequestHeader(DefaultBHttpServerConnection.java:130)
W/System.err:     at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:308)
W/System.err:     at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by napoleaon** [comment]
这或许是一个难题，很多开源的web服务器都会有这个问题，在接收大量post数据时候，接收不完整

**Comment by yanzhenjie** [comment]
很多开源web服务器都有这个问题，有没有可能是你使用姿势的问题？4058B也就是4k，随便发个数据就爆了，我这边传100M文件、发送个几M的JSON都没问题。你可以试试在dev分支发布的2.0.0版本，像SpringMVC一样用注解开发（基于编译时注解），不过文档明后天才能上线，文档上线后会合并到master分支。

例如局域网路由器承载能力、路由器稳定性，内网反而不像外网这么稳定。

**Comment by napoleaon** [comment]
感谢作者的回复，我试试2.0.0版本

**Comment by napoleaon** [comment]
我的推测啊，作者勿怪，我感觉是读取缓冲区的问题，在read socket 时候不知道对方的字节长度是多少，只读取一个缓冲区就结束了，没有读数据的结束标志，这种情况跟另外一个开源软件（https://github.com/qinyuanpei/HttpServer）C#类似，也是post数据接受不全

举例啊：
https://github.com/qinyuanpei/HttpServer/blob/master/HTTPServer/HTTPServerLib/HttpRequest.cs
httpserver 里面核心接收代码，下面的代码接收数据是不稳定的

 private string GetRequestData(Stream stream)
{
var length = 0;
var data = string.Empty;
do
{
length = stream.Read(bytes, 0, MAX_SIZE - 1);
data += Encoding.UTF8.GetString(bytes, 0, length);
} while (length > 0 && !data.Contains("\r\n\r\n"));
return data;
}

**Comment by napoleaon** [comment]
作者可以按照我测试的方法测试一下，看看能否重现该问题

**Comment by yanzhenjie** [comment]
异常是你缺少参数，那个接口规定了必须那个参数。

POST时我是将参数放在Body中的，一张图片8M，一张图片35K左右都是可以的。你是否是把图片base64后放在Url中？

**Comment by napoleaon** [comment]
url接受数据长度是2k左右， post数据是放在body中，我用的postman工具测试的，这个很规范了

**Comment by napoleaon** [comment]
异常是你缺少参数，那个接口规定了必须那个参数。-
---------------------------------------------------------
异常应该是参数问题，如你所说
 但是日志打印的imgbase64子段不全，应该是接受不完整所致
I/AndServerSample: Request: Path: /user/login; Param: {"imgBase64":

**Comment by yanzhenjie** [comment]
上述测试，你可以把Gif解开后一帧一帧看，开始复制时字符串的结尾和返回结果的自传结尾（GIF中我圈了一下）。

另外你上面的那个测试，Log打印时是有长度限制的，超过要换行，所以没显示全，所以说**你的测试也只没问题的**。

**Comment by napoleaon** [comment]
我试试看
