### ISSUE TITLE
无法启动Server [Android API 18,AndServer 2.0.1]

### ISSUE THREAD

**Issue by newdive** [yanzhenjie/AndServer#113]
AndServer 版本 2.0.1
Android版本 4.3 API 18
调用 Server.startup方法之后 Logcat打印日志如下
10-03 08:13:29.458 15577-15658/? I/AndServer: VM with version 1.6.0 does not have Multidex support.
10-03 08:13:29.468 15577-15658/? I/AndServer: InstantRun support was not found.
10-03 08:13:29.498 15577-15658/? I/AndServer: Loading com.yanzhenjie.andserver.register.AdapterRegister.

ServerListener的监听方法 onStarted、 onStopped、 onException  都没有被调用
请问是什么原因？

**Comment by newdive** [comment]
补充下
经过测试，API 19 - 23 版本都可以正常启动，其它版本暂时没试过。

**Comment by yetao-study** [comment]
你出现过这个问题吗？在Android版本 4.3 API 18上。
    java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
        at org.apache.commons.io.Charsets.<clinit>(Charsets.java:120)
        at com.yanzhenjie.andserver.Server$1.run(Server.java:101)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
        at java.lang.Thread.run(Thread.java:841)
