### ISSUE TITLE
java.nio.charset.StandardCharsets

### ISSUE THREAD

**Issue by zjianflys** [yanzhenjie/AndServer#167]
我用华为 android 8.0没有报错,用三星平板 android 4.2.2  报错
 ` java.lang.ExceptionInInitializerError
        at com.yanzhenjie.andserver.Server$1.run(Server.java:101)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
        at java.lang.Thread.run(Thread.java:856)
     Caused by: java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
        at org.apache.commons.io.Charsets.<clinit>(Charsets.java:120)
        at com.yanzhenjie.andserver.Server$1.run(Server.java:101) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
        at java.lang.Thread.run(Thread.java:856) `

网上搜了一下  说是编码的问题  但也不晓得怎么解决
`
                mHttpServer = ServerBootstrap.bootstrap()
                    .setSocketConfig(SocketConfig.custom()
                        .setSoKeepAlive(true)
                        .setSoReuseAddress(true)
                        .setSoTimeout(mTimeout)
                        .setTcpNoDelay(true)
                        .build())
                    .setConnectionConfig(
                        ConnectionConfig.custom().setBufferSize(4 * 1024).setCharset(Charsets.UTF_8).build())
                    .setLocalAddress(mInetAddress)
                    .setListenerPort(mPort)
                    .setSslContext(mSSLContext)
                    .setSslSetupHandler(new SSLInitializerWrapper(mSSLInitializer))
                    .setServerInfo("AndServer/2.0.0")
                    .registerHandler("*", handler)
                    .setExceptionLogger(ExceptionLogger.NO_OP)
                    .create();`

中的
` .setConnectionConfig(
                        ConnectionConfig.custom().setBufferSize(4 * 1024).setCharset(Charsets.UTF_8).build())`

这句换报错...
麻烦有时间的时候解决一下...

**Comment by yanzhenjie** [comment]
It looks like a 64k problem. [Enable multidex for apps with over 64K methods](https://developer.android.com/studio/build/multidex).
