### ISSUE TITLE
1.1.4版本不支持https，报Handshake failed

### ISSUE THREAD

**Issue by ThomsonOo** [yanzhenjie/AndServer#174]
服务器配置代码：
```java
mServer = AndServer.serverBuilder()
                .inetAddress(NetUtils.getLocalIPAddress())
                .sslContext(SSLContextUtils.getDefaultSLLContext())
                .port(8080)
                .timeout(10, TimeUnit.SECONDS)
                .registerHandler("/snap", new SnapHandler())
                .filter(new HttpCacheFilter())
                .listener(mListener)
                .build();
 startServer();
```

SSLContext自定义类
```java
import android.annotation.SuppressLint;
import android.content.Context;
import android.util.Log;

import java.io.InputStream;
import java.security.KeyStore;
import java.security.SecureRandom;
import java.security.cert.Certificate;
import java.security.cert.CertificateException;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;

import javax.net.ssl.HostnameVerifier;
import javax.net.ssl.KeyManagerFactory;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSession;
import javax.net.ssl.TrustManager;
import javax.net.ssl.TrustManagerFactory;
import javax.net.ssl.X509TrustManager;

public class SSLContextUtils {

    private static final String TAG = "SSLContextUtils";

    /**
     * 有证方式
     *
     * @param ctx
     * @return
     */
    @SuppressLint("TrulyRandom")
    public static SSLContext getSSLContext(Context ctx) {
        SSLContext sslContext = null;
        try {
            sslContext = SSLContext.getInstance("TLS");
            InputStream inputStream = ctx.getApplicationContext().getAssets().open("srca.cer");

            CertificateFactory cerFactory = CertificateFactory.getInstance("X.509");
            Certificate cer = cerFactory.generateCertificate(inputStream);

            KeyStore keyStore = KeyStore.getInstance("PKCS12");
            keyStore.load(null, null);
            keyStore.setCertificateEntry("trust", cer);

            KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance(
                    KeyManagerFactory.getDefaultAlgorithm());
            keyManagerFactory.init(keyStore, null);

            TrustManagerFactory trustManagerFactory =
                    TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
            trustManagerFactory.init(keyStore);

            sslContext.init(keyManagerFactory.getKeyManagers(), trustManagerFactory
                    .getTrustManagers(), new SecureRandom());

            inputStream.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return sslContext;
    }

    /**
     * 无证方式
     *
     * @return
     */
    public static SSLContext getDefaultSLLContext() {
        SSLContext sslContext = null;
        try {
            sslContext = SSLContext.getInstance("TLSv1.2");
            sslContext.init(null, new TrustManager[]{trustManagers}, new SecureRandom());
        } catch (Exception e) {
            e.printStackTrace();
        }
        return sslContext;
    }

    public static TrustManager getTrustManagers() {
        return trustManagers;
    }

    private static TrustManager trustManagers = new X509TrustManager() {

        @Override
        public void checkClientTrusted(X509Certificate[] chain, String authType) throws
                CertificateException {
            Log.d(TAG, "checkClientTrusted: authType -> " + authType);
        }

        @Override
        public void checkServerTrusted(X509Certificate[] chain, String authType) throws
                CertificateException {
            Log.d(TAG, "checkClientTrusted: authType -> " + authType);
        }

        @Override
        public X509Certificate[] getAcceptedIssuers() {
            return null;
        }
    };

    public static final HostnameVerifier HOSTNAME_VERIFIER = new HostnameVerifier() {

        @Override
        public boolean verify(String hostname, SSLSession session) {
            return true;
        }
    };
}

```

用postman或者自己写的Client请求服务器的接口，一直报握手失败
```java
javax.net.ssl.SSLHandshakeException: Handshake failed
04-08 19:59:50.470 27483-27547/com.xx.xx.xx W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:390)
04-08 19:59:50.470 27483-27547/com.xx.xx.xx W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:623)
04-08 19:59:50.470 27483-27547/com.xx.xx.xx W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:585)
04-08 19:59:50.470 27483-27547/com.xx.xx.xx W/System.err:     at org.apache.httpcore.impl.BHttpConnectionBase.getSocketInputStream(BHttpConnectionBase.java:142)
04-08 19:59:50.470 27483-27547/com.xx.xx.xx W/System.err:     at org.apache.httpcore.impl.BHttpConnectionBase.ensureOpen(BHttpConnectionBase.java:134)
04-08 19:59:50.470 27483-27547/com.xx.xx.xx W/System.err:     at org.apache.httpcore.impl.DefaultBHttpServerConnection.receiveRequestHeader(DefaultBHttpServerConnection.java:129)
04-08 19:59:50.470 27483-27547/com.xx.xx.xx W/System.err:     at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:308)
04-08 19:59:50.470 27483-27547/com.xx.xx.xx W/System.err:     at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
04-08 19:59:50.470 27483-27547/com.xx.xx.xx W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-08 19:59:50.470 27483-27547/com.xx.xx.xx W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-08 19:59:50.470 27483-27547/com.xx.xx.xx W/System.err:     at java.lang.Thread.run(Thread.java:818)
04-08 19:59:50.470 27483-27547/com.xx.xx.xx W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb88a7ec8: Failure in SSL library, usually a protocol error
04-08 19:59:50.471 27483-27547/com.xx.xx.xx W/System.err: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher (external/openssl/ssl/s3_srvr.c:1396 0xac20bf89:0x00000000)
04-08 19:59:50.471 27483-27547/com.xx.xx.xx W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
04-08 19:59:50.471 27483-27547/com.xx.xx.xx W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:318)
04-08 19:59:50.471 27483-27547/com.xx.xx.xx W/System.err: 	... 10 more
```

疑问：
我使用http的时候啥问题没有，项目现在要支持https，发现加上sslContext之后就一直请求出错。
是对AndServer的设置有问题？还是1.1.4的版本不支持https？
急需求，求严老师能帮忙解答一下，多谢！

**Comment by ThomsonOo** [comment]
@yanzhenjie

**Comment by yanzhenjie** [comment]
The handshake failed. This may be because the SSLContext configuration of the server is incorrect.

**Comment by ThomsonOo** [comment]
That's my I find the solution,

**Comment by lvleo** [comment]
@ThomsonOo  Thank you sharing. The solution works well in my project
