### ISSUE TITLE
Opening an oat file without a class loader. Are you using the deprecated DexFile APIs?

### ISSUE THREAD

**Issue by whoislxy** [yanzhenjie/AndServer#179]
2019-04-24 19:41:59.766 3336-5090/com.xxx W/zygote: Opening an oat file without a class loader. Are you using the deprecated DexFile APIs?
2019-04-24 19:41:59.768 3336-5090/com.xxx W/AndServer: An exception occurred while registering components.
    java.io.IOException: No original dex files found for dex location /data/app/com.xxx.xxx.package/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:86)
        at com.yanzhenjie.andserver.ComponentRegister.register(ComponentRegister.java:71)
        at com.yanzhenjie.andserver.Server$1.run(Server.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by yanzhenjie** [comment]
Does the framework work?

If it doesn't work, please provide the environmental information of the equipment running the project.

**Comment by whoislxy** [comment]
my devices is android 8.0 ，and the app is runing，not crash， so i want fix this problem！

**Comment by yanzhenjie** [comment]
AndServer tried to load some different dex files, which may only be a warning from AndServer and does not affect normal use.

**Comment by whoislxy** [comment]
ths
