### ISSUE TITLE
proxyServer可以和webServer同时开启么？

### ISSUE THREAD

**Issue by RockVampire** [yanzhenjie/AndServer#274]
mServer = AndServer.webServer(this)
                .port(8080)
                .timeout(10, TimeUnit.SECONDS)
                .build();

        String loaclhost = "http://" + NetUtils.getLocalIPAddress().getHostAddress() + ":8080";

        Log.e("localhost",loaclhost);

        proxyServer = AndServer.proxyServer()
                .addProxy("55.66.11.11", loaclhost)
                .port(80)
                .timeout(10, TimeUnit.SECONDS)
                .build();

我想在局域网内通过代理访问webServer，运行时出现如下错误提示

2020-05-25 15:42:49.249 3057-3085/com.aios.visandserver W/System.err: java.net.BindException: bind failed: EACCES (Permission denied)
2020-05-25 15:42:49.252 3057-3085/com.aios.visandserver W/System.err:     at libcore.io.IoBridge.bind(IoBridge.java:103)
2020-05-25 15:42:49.254 3057-3085/com.aios.visandserver W/System.err:     at java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:157)
2020-05-25 15:42:49.255 3057-3085/com.aios.visandserver W/System.err:     at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:427)
2020-05-25 15:42:49.257 3057-3085/com.aios.visandserver W/System.err:     at java.net.ServerSocket.bind(ServerSocket.java:377)
2020-05-25 15:42:49.257 3057-3085/com.aios.visandserver W/System.err:     at com.yanzhenjie.andserver.server.ProxyServer$HttpServer.startServer(ProxyServer.java:258)
2020-05-25 15:42:49.258 3057-3085/com.aios.visandserver W/System.err:     at com.yanzhenjie.andserver.server.ProxyServer$1.run(ProxyServer.java:132)
2020-05-25 15:42:49.258 3057-3085/com.aios.visandserver W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-05-25 15:42:49.258 3057-3085/com.aios.visandserver W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-05-25 15:42:49.259 3057-3085/com.aios.visandserver W/System.err:     at java.lang.Thread.run(Thread.java:764)
2020-05-25 15:42:49.259 3057-3085/com.aios.visandserver W/System.err: Caused by: android.system.ErrnoException: bind failed: EACCES (Permission denied)
2020-05-25 15:42:49.260 3057-3085/com.aios.visandserver W/System.err:     at libcore.io.Linux.bind(Native Method)
2020-05-25 15:42:49.260 3057-3085/com.aios.visandserver W/System.err:     at libcore.io.ForwardingOs.bind(ForwardingOs.java:60)
2020-05-25 15:42:49.261 3057-3085/com.aios.visandserver W/System.err:     at libcore.io.IoBridge.bind(IoBridge.java:99)
2020-05-25 15:42:49.261 3057-3085/com.aios.visandserver W/System.err: 	... 8 more

是不是webServer和proxyServer不能同时创建的原因呢？

**Comment by yanzhenjie** [comment]
可以同时开启，不能使用同一个端口，另外需要注意一部分端口被系统保留，比如80。
