### ISSUE TITLE
上传视频怎么突破大小限制?

### ISSUE THREAD

**Issue by zengyunpeng** [yanzhenjie/AndServer#296]
com.yanzhenjie.andserver.error.MaxUploadSizeExceededException: Maximum upload size of 20971520 bytes exceeded
     at com.yanzhenjie.andserver.http.multipart.StandardMultipartResolver.parseRequest(StandardMultipartResolver.java:143)
     at com.yanzhenjie.andserver.http.multipart.StandardMultipartResolver.resolveMultipart(StandardMultipartResolver.java:101)
     at com.yanzhenjie.andserver.DispatcherHandler.handle(DispatcherHandler.java:136)
     at com.yanzhenjie.andserver.DispatcherHandler.handle(DispatcherHandler.java:128)
     at org.apache.httpcore.protocol.HttpService.doService(HttpService.java:437)
     at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:342)
     at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)

上传视频文件报如上错误,这个有办法解决吗

**Comment by zengyunpeng** [comment]
自己回答一下:
@Config 注解可配置上传文件,数据大小
