### ISSUE TITLE
上传文件时出现 java.lang.NoClassDefFoundError 异常

### ISSUE THREAD

**Issue by rendcloud** [yanzhenjie/AndServer#3]
严老师您好:

今天在测试您的这个库时上传文件怎么都不成功,我使用post方式上传一个图片文件,在sample程序中会出现如下异常:

```java
FATAL EXCEPTION: pool-1-thread-1
                                                                                 Process: com.yanzhenjie.andserver.sample, PID: 26026
                                                                                 java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/commons/io/output/DeferredFileOutputStream;
                                                                                     at org.apache.commons.fileupload.disk.DiskFileItem.getOutputStream(DiskFileItem.java:538)
                                                                                     at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:369)
                                                                                     at com.yanzhenjie.andserver.sample.response.AndServerUploadHandler.processFileUpload(AndServerUploadHandler.java:90)
                                                                                     at com.yanzhenjie.andserver.sample.response.AndServerUploadHandler.handle(AndServerUploadHandler.java:62)
                                                                                     at com.yanzhenjie.andserver.DefaultHttpRequestHandler.handle(DefaultHttpRequestHandler.java:43)
                                                                                     at org.apache.http.protocol.HttpService.doService(HttpService.java:248)
                                                                                     at org.apache.http.protocol.HttpService.handleRequest(HttpService.java:192)
                                                                                     at com.yanzhenjie.andserver.RequestHandleTask.run(RequestHandleTask.java:49)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.io.output.DeferredFileOutputStream" on path: DexPathList[[zip file "/data/app/com.yanzhenjie.andserver.sample-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
                                                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                     at org.apache.commons.fileupload.disk.DiskFileItem.getOutputStream(DiskFileItem.java:538) 
                                                                                     at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:369) 
                                                                                     at com.yanzhenjie.andserver.sample.response.AndServerUploadHandler.processFileUpload(AndServerUploadHandler.java:90) 
                                                                                     at com.yanzhenjie.andserver.sample.response.AndServerUploadHandler.handle(AndServerUploadHandler.java:62) 
                                                                                     at com.yanzhenjie.andserver.DefaultHttpRequestHandler.handle(DefaultHttpRequestHandler.java:43) 
                                                                                     at org.apache.http.protocol.HttpService.doService(HttpService.java:248) 
                                                                                     at org.apache.http.protocol.HttpService.handleRequest(HttpService.java:192) 
                                                                                     at com.yanzhenjie.andserver.RequestHandleTask.run(RequestHandleTask.java:49) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                     at java.lang.Thread.run(Thread.java:818) 
                                                                                 	Suppressed: java.lang.ClassNotFoundException: org.apache.commons.io.output.DeferredFileOutputStream
                                                                                     at java.lang.Class.classForName(Native Method)
                                                                                     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
```
请问是我传的参数有问题吗?我已经按照您博客中的描述对sample程序添加了 ` useLibrary 'org.apache.http.legacy'`,sdk中也不缺失文件,希望您如果看到的话能在百忙中抽出时间不吝赐教

**Comment by rendcloud** [comment]
我自己找到了解决方法,就是在项目依赖中添加上`    compile 'commons-io:commons-io:1.4' `的依赖即可,注意不要去studio的dependencies中用maver的方式添加,那样找到的版本比这个要高,依然找不到这个出问题的类`DeferredFileOutputStream`,直接用1.4版本的即可解决此问题
