### ISSUE TITLE
异常

### ISSUE THREAD

**Issue by YuMinZe** [yanzhenjie/AndServer#332]
com.yanzhenjie.andserver.error.MethodNotSupportException: The request method [POST] is not supported.
at com.yanzhenjie.andserver.framework.handler.MappingAdapter.intercept(MappingAdapter.java:66)
at com.yanzhenjie.andserver.DispatcherHandler.getHandlerAdapter(DispatcherHandler.java:211)
at com.yanzhenjie.andserver.DispatcherHandler.handle(DispatcherHandler.java:140)
at com.yanzhenjie.andserver.DispatcherHandler.handle(DispatcherHandler.java:128)
at org.apache.httpcore.protocol.HttpService.doService(HttpService.java:437)
at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:342)
 at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)

**Comment by YuMinZe** [comment]
2.1.3升到2.1.6

**Comment by yanzhenjie** [comment]
你请求的Api不支持POST，这还不明显么.
