### ISSUE TITLE
本地访问出现地址不匹配

### ISSUE THREAD

**Issue by ucssi-dongxd** [yanzhenjie/AndServer#336]
你好，我使用2.1.3版本，未绑定ip地址，设置固定的端口为8000，
浏览器web访问。通过设备的真实ip地址能访问，但是本机软件通过访问http://127.0.0.1:8000/的方式失败，打印的log地址不一致。（设备未设置代理，使用的是有线网络连接-DHCP，应用中也没有设置代理）

![image](https://user-images.githubusercontent.com/61998433/100701530-d129d980-33da-11eb-800a-445b1790774b.png)

网络请求打印出来的地址也是127.0.0.1，但是请求超时提示的地址却不一样。

日志如下
`
12-01 12:00:44.939  2062  2062 W System.err: java.net.SocketTimeoutException: failed to connect to /192.168.146.210 (port 8888) from /192.168.146.215 (port 34288) after 30000ms
12-01 12:00:44.940  2062  2062 W System.err: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
12-01 12:00:44.940  2062  2062 W System.err: 	at libcore.io.IoBridge.connect(IoBridge.java:130)
12-01 12:00:44.940  2062  2062 W System.err: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
12-01 12:00:44.940  2062  2062 W System.err: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
12-01 12:00:44.940  2062  2062 W System.err: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
12-01 12:00:44.940  2062  2062 W System.err: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
12-01 12:00:44.940  2062  2062 W System.err: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:357)
12-01 12:00:44.940  2062  2062 W System.err: 	at java.net.Socket.connect(Socket.java:616)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:63)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:223)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
12-01 12:00:44.940  2062  2062 W System.err: 	at com.ucssi.door.net.HttpIntercept.intercept(HttpIntercept.java:59)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
12-01 12:00:44.940  2062  2062 W System.err: 	at okhttp3.RealCall.execute(RealCall.java:69)
12-01 12:00:44.941  2062  2062 W System.err: 	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
12-01 12:00:44.941  2062  2062 W System.err: 	at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(CallObservable.java:41)
12-01 12:00:44.941  2062  2062 W System.err: 	at io.reactivex.Observable.subscribe(Observable.java:12036)
12-01 12:00:44.941  2062  2062 W System.err: 	at com.jakewharton.retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
12-01 12:00:44.941  2062  2062 W System.err: 	at io.reactivex.Observable.subscribe(Observable.java:12036)
12-01 12:00:44.941  2062  2062 W System.err: 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
12-01 12:00:44.941  2062  2062 W System.err: 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
12-01 12:00:44.941  2062  2062 W System.err: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
12-01 12:00:44.941  2062  2062 W System.err: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
12-01 12:00:44.941  2062  2062 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-01 12:00:44.941  2062  2062 W System.err: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
12-01 12:00:44.941  2062  2062 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
12-01 12:00:44.941  2062  2062 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
12-01 12:00:44.941  2062  2062 W System.err: 	at java.lang.Thread.run(Thread.java:764)
`

**Comment by yanzhenjie** [comment]
应该就是本机环境问题，看下有没有网络代理的进程还活着，或者本机解析dns有问题；和框架没有关系的；
