### ISSUE TITLE
不同设备上uri变成乱码

### ISSUE THREAD

**Issue by andyxm** [yanzhenjie/AndServer#362]
GET /video/?address=/vod/æµè¯è§é¢/xiangmu/è¡éª¨å¤´åæ­».szem&site=172.168.32.8;172.168.32.9&type=order [Accept: */*, Range: bytes=0-, Connection: close, Host: 127.0.0.1:8081, User-Agent: AppleCoreMedia/1.0.0.7B367 (iPad; U; CPU OS 4_3_3 like Mac OS X)]

Illegal character in query at index 39: scheme://host:ip/video/?address=/vod/æµè¯è§é¢/xiangmu/è¡éª¨å¤´åæ­».szem&site=172.168.32.8;172.168.32.9&type=order

在其中一台设备上(android6.0.1)正常.另一台设备上(android8.1.0)就会包这个错误

**Comment by yanzhenjie** [comment]
上面贴的是抓包吧？看这个格式应该是客户端发起请求时就乱码的？
你这边的异常是哪端抛出来的?具体堆栈也发一下

**Comment by andyxm** [comment]
是客户端发请求时候,用在android本身做视频转发的请求,debug时,是没有乱码的
java.lang.IllegalArgumentException: Illegal character in query at index 39: scheme://host:ip/video/?address=/vod/æµè¯è§é¢/xiangmu/è¡éª¨å¤´åæ­».szem&site=172.168.32.8;172.168.32.9&type=order
    at java.net.URI.create(URI.java:847)
    at com.yanzhenjie.andserver.http.Uri$Builder.<init>(Uri.java:208)
    at com.yanzhenjie.andserver.http.Uri$Builder.<init>(Uri.java:198)
    at com.yanzhenjie.andserver.http.Uri.newBuilder(Uri.java:70)
    at com.yanzhenjie.andserver.http.StandardRequest.parseUri(StandardRequest.java:145)
    at com.yanzhenjie.andserver.http.StandardRequest.getPath(StandardRequest.java:157)
    at com.yanzhenjie.andserver.framework.handler.MappingAdapter.intercept(MappingAdapter.java:49)
    at com.yanzhenjie.andserver.DispatcherHandler.getHandlerAdapter(DispatcherHandler.java:211)
    at com.yanzhenjie.andserver.DispatcherHandler.handle(DispatcherHandler.java:140)
    at com.yanzhenjie.andserver.DispatcherHandler.handle(DispatcherHandler.java:128)
    at org.apache.httpcore.protocol.HttpService.doService(HttpService.java:437)
    at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:342)
    at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
Caused by: java.net.URISyntaxException: Illegal character in query at index 39: scheme://host:ip/video/?address=/vod/æµè¯è§é¢/xiangmu/è¡éª¨å¤´åæ­».szem&site=172.168.32.8;172.168.32.9&type=order
    at java.net.URI$Parser.fail(URI.java:2875)
    at java.net.URI$Parser.checkChars(URI.java:3048)
    at java.net.URI$Parser.parseHierarchical(URI.java:3138)
    at java.net.URI$Parser.parse(URI.java:3080)
    at java.net.URI.<init>(URI.java:583)
    at java.net.URI.create(URI.java:845)
	... 15 more
java.lang.IllegalArgumentException: Illegal character in query at index 39: scheme://host:ip/video/?address=/vod/æµè¯è§é¢/xiangmu/è¡éª¨å¤´åæ­».szem&site=172.168.32.8;172.168.32.9&type=order
    at java.net.URI.create(URI.java:847)
    at com.yanzhenjie.andserver.http.Uri$Builder.<init>(Uri.java:208)
    at com.yanzhenjie.andserver.http.Uri$Builder.<init>(Uri.java:198)
    at com.yanzhenjie.andserver.http.Uri.newBuilder(Uri.java:70)
    at com.yanzhenjie.andserver.http.StandardRequest.parseUri(StandardRequest.java:145)
    at com.yanzhenjie.andserver.http.StandardRequest.getPath(StandardRequest.java:157)
    at com.yanzhenjie.andserver.framework.handler.MappingAdapter.intercept(MappingAdapter.java:49)
    at com.yanzhenjie.andserver.DispatcherHandler.getHandlerAdapter(DispatcherHandler.java:211)
    at com.yanzhenjie.andserver.DispatcherHandler.handle(DispatcherHandler.java:140)
    at com.yanzhenjie.andserver.DispatcherHandler.handle(DispatcherHandler.java:128)
    at org.apache.httpcore.protocol.HttpService.doService(HttpService.java:437)
    at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:342)
    at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
Caused by: java.net.URISyntaxException: Illegal character in query at index 39: scheme://host:ip/video/?address=/vod/æµè¯è§é¢/xiangmu/è¡éª¨å¤´åæ­».szem&site=172.168.32.8;172.168.32.9&type=order
    at java.net.URI$Parser.fail(URI.java:2875)
    at java.net.URI$Parser.checkChars(URI.java:3048)
    at java.net.URI$Parser.parseHierarchical(URI.java:3138)
    at java.net.URI$Parser.parse(URI.java:3080)
    at java.net.URI.<init>(URI.java:583)
    at java.net.URI.create(URI.java:845)
	... 15 more

**Comment by yanzhenjie** [comment]
代码贴一下

**Comment by andyxm** [comment]
private String remoteBaseUrl = "http://127.0.0.1:8081/video/?address=%s&site=%s&type=order";
    //address        服务器文件地址
    private String remoteVideoPath = "/vod/测试视频/xiangmu/股骨头坏死.szem";
    //site  服务器ip多个ip以;分割
    private String remoteServerIp = "172.168.32.8;172.168.32.9";
    private String remotePlayerPath = String.format(remoteBaseUrl, remoteVideoPath, remoteServerIp);

   mUri = Uri.parse(remotePlayerPath );
   mMediaPlayer.setDataSource(this.getContext(), mUri);//


 貌似还没到下边这一步呢,也没别的了
 @GetMapping(path = "/video")
    ResponseBody site(HttpRequest request, HttpResponse response) throws IOException {
        HttpURLConnection connection;
        BufferedInputStream stream;
        String httpPath = request.getPath();
        //视频地址名称
        String address = request.getParameter("address");
        //服务器地址集合
        String site = request.getParameter("site");

//        String type = request.getParameter("type");

        Log.d(TAG, String.format("requestPath:%s address:%s site:%s", httpPath, address, site));

//        int lastIndexOf = address.lastIndexOf("/");
//
//        String path = address.substring(0, lastIndexOf + 1);
//
//        String videoName = address.substring(lastIndexOf + 1);
//
//        Log.d(TAG, String.format("path:%s videoName:%s", path, videoName));

        String[] serverAddress = site.split(";");

        String url = String.format("http://%s%s", serverAddress[0], URLEncoderUtils.urlEncode(address));

        Log.d(TAG, "url->" + url);

        URL httpUrl = new URL(url);
        connection = (HttpURLConnection) httpUrl.openConnection();
//        connection.setReadTimeout(10*1000);
//        connection.setConnectTimeout(10*1000);
//        connection.connect();
        if (!isResponseCode0K(connection) && serverAddress.length == 2) {
            url = String.format("http://%s%s", serverAddress[1], URLEncoderUtils.urlEncode(address));
            httpUrl = new URL(url);
            connection = (HttpURLConnection) httpUrl.openConnection();
            isResponseCode0K(connection);
        }
        int httpLength = connection.getContentLength();
        stream = new BufferedInputStream(connection.getInputStream());
        String range = request.getHeader("Range");
        Log.i(TAG, "Range:" + range + ",httpLength:" + httpLength);

//        boolean isWriteFileResult = FileIOUtils.writeFileFromIS("/sdcard/aaa.mp4", stream);
//        Log.d(TAG, "isWriteFileResult: "+isWriteFileResult);
       .......
        return new HttpBody(stream, httpLength, MediaType.getFileMediaType(address));

**Comment by yanzhenjie** [comment]
视频地址做urlEncode后再试试，另外你这个获取参数的姿势可以换成注解的，多方便啊。

**Comment by andyxm** [comment]
实现将url转了一下 可以了,感谢
