### ISSUE TITLE
下载文件

### ISSUE THREAD

**Issue by tobin8y** [yanzhenjie/AndServer#376]
``` java
@Controller
public class FileController {

    @RequestMapping(path = "/file/download", method = {RequestMethod.GET, RequestMethod.POST})
    public void download(@RequestParam(name = "path", required = false) String path,
                         @RequestParam(name = "filename") String filename,
                         HttpResponse response) {
        File localFolder = new File(App.getInstance().getRootDir().getAbsolutePath()+ path);
        File localFile = new File(localFolder.getAbsolutePath()+ "/" + filename);
        Logger.i("downloadFile >>> localFile: " + localFile);
        if (!localFile.exists()) {
            Logger.i("downloadFile >>> file does not exist");
            return;
        }
        ResponseBody body = new FileBody(localFile);
        response.setBody(body);
        //response.addHeader("Content-Type", "application/octet-stream");
        //response.addHeader("Content-disposition", "attachment; filename=" + filename);
    }
}
```

W/System.err: com.yanzhenjie.andserver.error.ServerInternalException: Server internal error, The return value of [null] is not supported.
        at com.yanzhenjie.andserver.framework.view.ViewResolver.resolvePath(ViewResolver.java:133)
        at com.yanzhenjie.andserver.framework.view.ViewResolver.resolve(ViewResolver.java:68)
        at com.yanzhenjie.andserver.DispatcherHandler.handle(DispatcherHandler.java:160)
        at com.yanzhenjie.andserver.DispatcherHandler.handle(DispatcherHandler.java:128)
        at org.apache.httpcore.protocol.HttpService.doService(HttpService.java:437)
        at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:342)
        at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

@Controller无返回值，会有内部错误 The return value of [null] is not supported.，response.setBody(FileBody)前端也没有接收到对应的文件，应该如何返回文件呢？

**Comment by AzAdkins** [comment]
在方法前面加载@ResponseBody注解试试，但是我用你这种设置ResponseBody的方法返回头的Content-Length为0，如果你只是单纯的下载文件，不涉及到断点续传的话，方法直接返回FileBody是可以下载的。

**Comment by tobin8y** [comment]
加`@Responsebody`注解后，方法等同于`@RestController`，返回的内容会经过`MessageConverter`，那个convert重载函数要怎么弄，直接`return new FileBody((File) output)`也不行

**Comment by AzAdkins** [comment]
MessageConverter不用写

**Comment by tobin8y** [comment]
嗯我试了下，直接返回FileBody对象是可以下载的

**Comment by AzAdkins** [comment]
那么问题来了，怎样支持断点续传呢，我现在就遇到这个问题了 #375
