### ISSUE TITLE
设置SSLContext报空指针异常

### ISSUE THREAD

**Issue by 6YingJie** [yanzhenjie/AndServer#379]
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/23075893/117522108-1d112800-afe4-11eb-82fe-3055724a4eb4.png">

这是我SSLContext生成的代码

     private SSLContext getSSLContext() {

        try {
            // key store相关信息
            String STORETYPE = "PKCS12";
            String KEYSTORE = "_.51vmr.com.pfx";
            String STOREPASSWORD = "123";
            String KEYPASSWORD = "123";

            KeyStore ks = KeyStore.getInstance(STORETYPE);
            ks.load(getAssets().open(KEYSTORE), STOREPASSWORD.toCharArray());

            KeyManagerFactory kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
            kmf.init(ks, KEYPASSWORD.toCharArray());

            TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
            tmf.init(ks);

            SSLContext sslContext = SSLContext.getInstance("TLS");
            sslContext.init(kmf.getKeyManagers(), tmf.getTrustManagers(), null);
            return sslContext;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

异常日志如下：
2021-05-08 09:54:07.464 8471-8471/com.zijingcloud.mt130 W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'void com.yanzhenjie.andserver.SSLSocketInitializer.onCreated(javax.net.ssl.SSLServerSocket)' on a null object reference
2021-05-08 09:54:07.464 8471-8471/com.zijingcloud.mt130 W/System.err:     at com.yanzhenjie.andserver.server.BasicServer$SSLSetup.initialize(BasicServer.java:180)
2021-05-08 09:54:07.464 8471-8471/com.zijingcloud.mt130 W/System.err:     at org.apache.httpcore.impl.bootstrap.HttpServer.start(HttpServer.java:121)
2021-05-08 09:54:07.464 8471-8471/com.zijingcloud.mt130 W/System.err:     at com.yanzhenjie.andserver.server.BasicServer$1.run(BasicServer.java:106)
2021-05-08 09:54:07.464 8471-8471/com.zijingcloud.mt130 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2021-05-08 09:54:07.464 8471-8471/com.zijingcloud.mt130 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2021-05-08 09:54:07.464 8471-8471/com.zijingcloud.mt130 W/System.err:     at java.lang.Thread.run(Thread.java:761)

**Comment by 6YingJie** [comment]
设置sslSocketInitializer就好了

**Comment by Guohaonan1** [comment]
我也遇到这个问题了，请问怎么设置sslSocketInitializer
