### ISSUE TITLE
接口函数怎么样才能支持kotlin的挂起函数suspend？

### ISSUE THREAD

**Issue by D10NGYANG** [yanzhenjie/AndServer#432]
```
    /**
     * 请求启动的服务器+状态列表
     * @return String
     */
    @GetMapping(path = ["/servers"])
    suspend fun getServers(): String {
        val dao = MyApp.instance().db.getMqttServerDao()
        val servers = dao.susQuery(true)
        val json = Http.json.encodeToJsonElement(servers)
        return json.toString()
    }
```
编译时报错：

Caused by: java.lang.IllegalStateException: The parameter type [kotlin.coroutines.Continuation<? super java.lang.String>] is not supported on com.x.web.HomeApiController#getServers().
	at com.yanzhenjie.andserver.processor.ControllerProcessor.createHandler(ControllerProcessor.java:1217)
	at com.yanzhenjie.andserver.processor.ControllerProcessor.createHandlerAdapter(ControllerProcessor.java:315)
	at com.yanzhenjie.andserver.processor.ControllerProcessor.process(ControllerProcessor.java:229)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:188)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)
	... 43 more

**Comment by yanzhenjie** [comment]
本来就是在子线程运行，你要挂起做什么呢，你可以直接在这里同步读写文件和请求网络都是没问题的。

**Comment by D10NGYANG** [comment]
> 本来就是在子线程运行，你要挂起做什么呢，你可以直接在这里同步读写文件和请求网络都是没问题的。

因为数据库用的room，读取的代码就是挂起函数，再加上很多其他方法已经是挂起函数了，直接在里头调用就回有编译器错误。

不过，改用ktor server做API服务器了，这个原生支持挂起函数。AndServer用来做web网页服务器就比较OK

**Comment by yanzhenjie** [comment]
OK，在AndServer里可以直接使用同步读取，比挂起更加方便。
