### ISSUE TITLE
每发起一个HTTP请求，都会出现超时：SocketTimeoutException

### ISSUE THREAD

**Issue by tourdt** [yanzhenjie/AndServer#66]

**Comment by viperasi** [comment]
同样，同时页面上的css和js无法加载，具体错误如下.
`04-12 16:57:01.188 1287-1907/com.xinyuan.guardapp W/System.err: java.net.SocketTimeoutException
        at java.net.PlainSocketImpl.read(PlainSocketImpl.java:491)
        at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
04-12 16:57:01.198 1287-1907/com.xinyuan.guardapp W/System.err:     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
04-12 16:57:01.208 1287-1907/com.xinyuan.guardapp W/System.err:     at org.apache.httpcore.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
04-12 16:57:01.218 1287-1907/com.xinyuan.guardapp W/System.err:     at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:130)
        at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:54)
04-12 16:57:01.228 1287-1907/com.xinyuan.guardapp W/System.err:     at org.apache.httpcore.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.httpcore.impl.DefaultBHttpServerConnection.receiveRequestHeader(DefaultBHttpServerConnection.java:130)
        at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:308)
        at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
04-12 16:57:02.698 1287-1906/com.xinyuan.guardapp W/System.err: java.net.SocketTimeoutException
        at java.net.PlainSocketImpl.read(PlainSocketImpl.java:491)
04-12 16:57:02.718 1287-1906/com.xinyuan.guardapp W/System.err:     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
        at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
04-12 16:57:02.728 1287-1906/com.xinyuan.guardapp W/System.err:     at org.apache.httpcore.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
        at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:130)
        at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:54)
        at org.apache.httpcore.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.httpcore.impl.DefaultBHttpServerConnection.receiveRequestHeader(DefaultBHttpServerConnection.java:130)
        at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:308)
04-12 16:57:02.738 1287-1906/com.xinyuan.guardapp W/System.err:     at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
04-12 16:57:03.298 1287-1909/com.xinyuan.guardapp W/System.err: java.net.SocketTimeoutException
04-12 16:57:03.318 1287-1909/com.xinyuan.guardapp W/System.err:     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:491)
        at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
04-12 16:57:03.328 1287-1909/com.xinyuan.guardapp W/System.err:     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
        at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:130)
        at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:54)
        at org.apache.httpcore.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
04-12 16:57:03.338 1287-1909/com.xinyuan.guardapp W/System.err:     at org.apache.httpcore.impl.DefaultBHttpServerConnection.receiveRequestHeader(DefaultBHttpServerConnection.java:130)
        at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:308)
        at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)`

**Comment by yanzhenjie** [comment]
你提供的信息没法判断。

**Comment by tourdt** [comment]
04-12 17:07:02.812 4472-5004/com.targzon.websvr W/System.err: java.net.SocketTimeoutException
04-12 17:07:02.812 4472-5004/com.targzon.websvr W/System.err:     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
04-12 17:07:02.812 4472-5004/com.targzon.websvr W/System.err:     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
04-12 17:07:02.812 4472-5004/com.targzon.websvr W/System.err:     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
04-12 17:07:02.812 4472-5004/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
04-12 17:07:02.812 4472-5004/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
04-12 17:07:02.812 4472-5004/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
04-12 17:07:02.812 4472-5004/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:130)
04-12 17:07:02.812 4472-5004/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:54)
04-12 17:07:02.812 4472-5004/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
04-12 17:07:02.812 4472-5004/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.DefaultBHttpServerConnection.receiveRequestHeader(DefaultBHttpServerConnection.java:130)
04-12 17:07:02.812 4472-5004/com.targzon.websvr W/System.err:     at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:308)
04-12 17:07:02.812 4472-5004/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
04-12 17:07:02.812 4472-5004/com.targzon.websvr W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-12 17:07:02.812 4472-5004/com.targzon.websvr W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-12 17:07:02.812 4472-5004/com.targzon.websvr W/System.err:     at java.lang.Thread.run(Thread.java:818)
04-12 17:07:02.812 4472-5005/com.targzon.websvr W/System.err: java.net.SocketTimeoutException
04-12 17:07:02.812 4472-5005/com.targzon.websvr W/System.err:     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
04-12 17:07:02.812 4472-5005/com.targzon.websvr W/System.err:     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
04-12 17:07:02.812 4472-5005/com.targzon.websvr W/System.err:     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
04-12 17:07:02.812 4472-5005/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
04-12 17:07:02.812 4472-5005/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
04-12 17:07:02.812 4472-5005/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
04-12 17:07:02.812 4472-5005/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:130)
04-12 17:07:02.812 4472-5005/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:54)
04-12 17:07:02.812 4472-5005/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
04-12 17:07:02.812 4472-5005/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.DefaultBHttpServerConnection.receiveRequestHeader(DefaultBHttpServerConnection.java:130)
04-12 17:07:02.812 4472-5005/com.targzon.websvr W/System.err:     at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:308)
04-12 17:07:02.812 4472-5005/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
04-12 17:07:02.822 4472-5005/com.targzon.websvr W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-12 17:07:02.822 4472-5005/com.targzon.websvr W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-12 17:07:02.822 4472-5005/com.targzon.websvr W/System.err:     at java.lang.Thread.run(Thread.java:818)
04-12 17:07:02.972 4472-5002/com.targzon.websvr W/System.err: java.net.SocketTimeoutException
04-12 17:07:02.972 4472-5002/com.targzon.websvr W/System.err:     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
04-12 17:07:02.972 4472-5002/com.targzon.websvr W/System.err:     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
04-12 17:07:02.972 4472-5002/com.targzon.websvr W/System.err:     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
04-12 17:07:02.972 4472-5002/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
04-12 17:07:02.972 4472-5002/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
04-12 17:07:02.972 4472-5002/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
04-12 17:07:02.972 4472-5002/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:130)
04-12 17:07:02.972 4472-5002/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:54)
04-12 17:07:02.972 4472-5002/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
04-12 17:07:02.972 4472-5002/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.DefaultBHttpServerConnection.receiveRequestHeader(DefaultBHttpServerConnection.java:130)
04-12 17:07:02.972 4472-5002/com.targzon.websvr W/System.err:     at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:308)
04-12 17:07:02.972 4472-5002/com.targzon.websvr W/System.err:     at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
04-12 17:07:02.972 4472-5002/com.targzon.websvr W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-12 17:07:02.972 4472-5002/com.targzon.websvr W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-12 17:07:02.972 4472-5002/com.targzon.websvr W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by tourdt** [comment]
我没发起一个请求，AndServer也成功返回了，但是过一会，就会报超时异常

**Comment by yanzhenjie** [comment]
返回的这个超时可以忽略。
无法加载的这个错误，能否提供具体的代码，还是说demo里面报的错？如果demo运行起来没这个错，请对照文档和demo检查一下你们的代码。

**Comment by viperasi** [comment]
直接用的simple demo， 放的是自己写的js和css，css和js经常出现net::ERR_CONNECTION_RESET错误，需要刷新好几次才有可能成功。
css文件大小96k, js是jquery库85k

**Comment by yanzhenjie** [comment]
你们网络是不是不稳定，提示网络reset了。提供的demo下载文件或者请求图片比这个文件大的多，没出现过不能访问的错误。有出现过超时，但是不会影响什么。

**Comment by viperasi** [comment]
不是啊，相同的环境，我是先运行的原始simple确实没有问题，然后替换了index.html，添加了css和js，就出现了问题。硬件环境上：局域网（无线/有线都测试了），512M运行内存，全志A33 CPU。

**Comment by yanzhenjie** [comment]
是开发板吗？你添加个文件浏览器的那个试试，文档有说这个。

**Comment by viperasi** [comment]
对，是开发板。直接写FileHandler？ 我试试，多谢。

**Comment by yanzhenjie** [comment]
有一个`FileBrowser`的`WebSite`的实现。

**Comment by viperasi** [comment]
说的是FileBrowser？但是我想弄一个网页啊。或者说css跟js的引用使用完整路径那种？

**Comment by yanzhenjie** [comment]
就是测试看看有没有问题，因为这个问题如果出现频繁，是比较严重的问题，应该早就有人反馈了，目前没有人反馈过。

**Comment by viperasi** [comment]
应该是没有人用这个环境吧。

**Comment by yanzhenjie** [comment]
net::ERR_CONNECTION_RESET这种很可能网络不稳定或者代理造成的。但是不排除AndServer的问题，我会继续排查AndServer的问题，如果目前不能满足的需求的话，建议转训其它解决方案。

**Comment by viperasi** [comment]
我之前有试过超时时间问题，修改成20秒也是不行，而且不能修改的太大，修改成50也会报一个错误。感觉主要问题还是文件过大，刚才去看了下simple里的图片和css都很小，也就是10K.这两个文件都接近100K了。

**Comment by yanzhenjie** [comment]
`FileBrowser`下载SD卡中的文件，几十兆都没问题。`FileHandler`传输文件时几百兆都可以的，这些都是做过测试的。

**Comment by viperasi** [comment]
把超时时间改成50秒就没有这个问题，但是SocketTimeout的异常依然有，只是网页不会再卡了，很快就能打开。

**Comment by ChineseBoyLY** [comment]
对，我也遇到，一直报SocketTimeout，但是不影响使用

**Comment by 897903718** [comment]
我这边也遇到这个问题 每次请求都会SocketTimeout 但是不影响使用
com.hongshi.andserverdemo W/System.err: java.net.SocketTimeoutException
        at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
        at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
        at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
        at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:130)
        at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:54)
        at org.apache.httpcore.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.httpcore.impl.DefaultBHttpServerConnection.receiveRequestHeader(DefaultBHttpServerConnection.java:130)

**Comment by panyongde** [comment]
我也遇到类似问题，加载jquery库和css经常性失败
