### ISSUE TITLE
一直出现 Read timed out 版本 1.1.0

### ISSUE THREAD

**Issue by cai784921129** [yanzhenjie/AndServer#75]
05-03 08:31:09.309 14444-14624/? W/System.err: java.net.SocketTimeoutException: Read timed out
05-03 08:31:09.310 14444-14624/? W/System.err:     at java.net.SocketInputStream.socketRead0(Native Method)
05-03 08:31:09.310 14444-14624/? W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:151)
05-03 08:31:09.310 14444-14624/? W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:120)
05-03 08:31:09.311 14444-14624/? W/System.err:     at org.apache.httpcore.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
05-03 08:31:09.311 14444-14624/? W/System.err:     at org.apache.httpcore.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
05-03 08:31:09.311 14444-14624/? W/System.err:     at org.apache.httpcore.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
05-03 08:31:09.311 14444-14624/? W/System.err:     at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:130)
05-03 08:31:09.311 14444-14624/? W/System.err:     at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:54)
05-03 08:31:09.311 14444-14624/? W/System.err:     at org.apache.httpcore.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:258)
05-03 08:31:09.311 14444-14624/? W/System.err:     at org.apache.httpcore.impl.DefaultBHttpServerConnection.receiveRequestHeader(DefaultBHttpServerConnection.java:131)
05-03 08:31:09.312 14444-14624/? W/System.err:     at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:308)
05-03 08:31:09.312 14444-14624/? W/System.err:     at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
05-03 08:31:09.312 14444-14624/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-03 08:31:09.312 14444-14624/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-03 08:31:09.312 14444-14624/? W/System.err:     at java.lang.Thread.run(Thread.java:761)

**Comment by zwk1729** [comment]
07-25 16:58:21.125 20507-3014/com.kedacom.httpserver W/System.err: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:151)
        at java.net.SocketInputStream.read(SocketInputStream.java:120)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
07-25 16:58:21.126 20507-3014/com.kedacom.httpserver W/System.err:     at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:130)
        at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:54)
        at org.apache.httpcore.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.httpcore.impl.DefaultBHttpServerConnection.receiveRequestHeader(DefaultBHttpServerConnection.java:130)
        at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:308)
        at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

**Comment by zwk1729** [comment]
我的也是，用的是Demo 的
