### ISSUE TITLE
总是超时？接收请求总是返回500

### ISSUE THREAD

**Issue by luoshiduan** [yanzhenjie/AndServer#94]
08-14 19:55:31.047 3800-4054/cn.com.mhearts.server W/System.err: java.net.SocketTimeoutException: Read timed out
08-14 19:55:31.049 3800-4054/cn.com.mhearts.server W/System.err:     at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:151)
        at java.net.SocketInputStream.read(SocketInputStream.java:120)
08-14 19:55:31.050 3800-4054/cn.com.mhearts.server W/System.err:     at org.apache.httpcore.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
        at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:130)
        at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:54)
        at org.apache.httpcore.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.httpcore.impl.DefaultBHttpServerConnection.receiveRequestHeader(DefaultBHttpServerConnection.java:130)
        at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:308)
        at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
08-14 19:55:31.051 3800-4054/cn.com.mhearts.server W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
08-14 19:55:31.324 3800-4053/cn.com.mhearts.server W/System.err: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:151)
        at java.net.SocketInputStream.read(SocketInputStream.java:120)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
        at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:130)
        at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:54)
        at org.apache.httpcore.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.httpcore.impl.DefaultBHttpServerConnection.receiveRequestHeader(DefaultBHttpServerConnection.java:130)
08-14 19:55:31.325 3800-4053/cn.com.mhearts.server W/System.err:     at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:308)
        at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
08-14 19:55:58.459 3800-4194/cn.com.mhearts.server W/System.err: java.net.SocketTimeoutException: Read timed out
08-14 19:55:58.460 3800-4194/cn.com.mhearts.server W/System.err:     at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:151)
        at java.net.SocketInputStream.read(SocketInputStream.java:120)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.httpcore.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
        at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:130)
        at org.apache.httpcore.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:54)
        at org.apache.httpcore.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.httpcore.impl.DefaultBHttpServerConnection.receiveRequestHeader(DefaultBHttpServerConnection.java:130)
        at org.apache.httpcore.protocol.HttpService.handleRequest(HttpService.java:308)
        at org.apache.httpcore.impl.bootstrap.Worker.run(Worker.java:66)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

**Comment by luoshiduan** [comment]
这些错误打印是正常。500是内部处理的有问题

**Comment by luoshiduan** [comment]
这些错误打印是正常。500是我自己内部处理的有问题。我自己的原因
